### PR TITLE
ALP-60 Standardized CSS

### PR DESCRIPTION
**Pull request by justinkkwan**

### CODE REVIEW

**Review by thaingocnguyen — APPROVED** [review]
This is awesome, thanks for doing this Justin! The only comment I have is should we rename App.css to styles.css so it's clear that App.css contain the styles for the entire app?

**Comment by justinkkwan** [comment]
> 
> 
> This is awesome, thanks for doing this Justin! The only comment I have is should we rename App.css to styles.css so it's clear that App.css contain the styles for the entire app?

Done!

**Review by michaelfromyeg — CHANGES_REQUESTED** [review]
Looks really good! I think we could reduce the amount of code needed in styles.css if we change the global primary and secondary colors (rather than individually restyling each component)--the easiest way to do this would probably be with a theme (I'm not certain if this is possible with CSS alone). This would also fix a few components that still haven't been styled (the radio component and the select component). Not super related to this PR but I think it's a small quick fix that should be done before merging.

https://material-ui.com/customization/theming/

**Comment by justinkkwan** [comment]
> 
> 
> Looks really good! I think we could reduce the amount of code needed in styles.css if we change the global primary and secondary colors (rather than individually restyling each component)--the easiest way to do this would probably be with a theme (I'm not certain if this is possible with CSS alone). This would also fix a few components that still haven't been styled (the radio component and the select component). Not super related to this PR but I think it's a small quick fix that should be done before merging.
> 
> https://material-ui.com/customization/theming/

I don't think that it's possible to have global primary/secondary colors with just the css file (which is a CTC requirement for all web apps, I think).

**Review by michaelfromyeg — APPROVED** [review]
Changes I rec'd were bumped to a new issue, so this is ready to be merged!

**Comment by justinkkwan** [comment]
> 
> 
> Looks really good! I think we could reduce the amount of code needed in styles.css if we change the global primary and secondary colors (rather than individually restyling each component)--the easiest way to do this would probably be with a theme (I'm not certain if this is possible with CSS alone). This would also fix a few components that still haven't been styled (the radio component and the select component). Not super related to this PR but I think it's a small quick fix that should be done before merging.
> 
> https://material-ui.com/customization/theming/

I'm dumb and did not see your other sentence 😢. I've now fixed the radio buttons, and the select box is going to be a new AutoCompleteSelectBox that @Leonlui  is working on

**Pull request merged**
